export const DEFAULT_GROUP_PURCHASE_PRODUCTS = [
  {
    id: "gdeal_1",
    sellerId: "seller_tech_mall",
    seller: "TechMall",
    title: "Smartwatch Alpha 2",
    price: 2000,
    segment: "group-purchase",
    transactionType: "pledge",
    type: "image",
    url: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=600&q=80",
    description: "Group Buying: Pledge to buy this smartwatch. If we hit 100 pledges, price drops to ₹1500!",
    isVerified: true,
    reviewCount: 45,
    ratingSum: 200,
    minPledgeCount: 100,
    currentPledgeCount: 34,
    pricePerPersonAtMin: 1500,
    expiryDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    category: "Group Buying",
  },
  {
    id: "gdeal_2",
    sellerId: "seller_food_supplies",
    seller: "FoodSupplies",
    title: "50kg Premium Sona Masoori Rice",
    price: 3000,
    segment: "group-purchase",
    transactionType: "bulk-buy",
    type: "image",
    url: "https://images.unsplash.com/photo-1586201375761-83865001e8ac?auto=format&fit=crop&w=600&q=80",
    description: "Bulk Order: Best for hostel mess or large family. Min order is 25kg.",
    isVerified: true,
    reviewCount: 88,
    ratingSum: 400,
    minOrderQuantity: 25,
    category: "Bulk Order"
  },
  {
    id: "gdeal_3",
    sellerId: "seller_escape",
    seller: "MysteryRooms",
    title: "Escape Room Adventure - Group Pass",
    price: 500,
    segment: "group-purchase",
    transactionType: "split",
    type: "image",
    url: "https://images.unsplash.com/photo-1518972559570-7cc1309f3229?auto=format&fit=crop&w=600&q=80",
    description: "Shared Experience: Split the cost among your friends. Needs minimum 5 people to start the adventure.",
    isVerified: true,
    reviewCount: 10,
    ratingSum: 45,
    minPledgeCount: 5,
    currentPledgeCount: 1,
    pricePerPersonAtMin: 400,
    category: "Shared Experience"
  },
  {
    id: "gdeal_4",
    sellerId: "seller_clean",
    seller: "CleanCo",
    title: "Deep House Cleaning Service",
    price: 2500,
    segment: "group-purchase",
    transactionType: "unlock",
    type: "image",
    url: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=80",
    description: "Community Offers: Apartment complex exclusive. If 10 flats book together, everyone unlocks the deal for ₹1800.",
    isVerified: true,
    reviewCount: 120,
    ratingSum: 580,
    minPledgeCount: 10,
    currentPledgeCount: 8,
    pricePerPersonAtMin: 1800,
    category: "Community Offers"
  },
  {
    id: "gdeal_5",
    sellerId: "seller_meal",
    seller: "HealthyMeals",
    title: "Monthly Diet Meal Subscription",
    price: 4000,
    segment: "group-purchase",
    transactionType: "refer-earn",
    type: "image",
    url: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80",
    description: "Referral Squad: Invite friends to join your plan. Everyone gets ₹500 off when your squad reaches 5 members.",
    isVerified: true,
    reviewCount: 65,
    ratingSum: 300,
    minPledgeCount: 5,
    currentPledgeCount: 2,
    pricePerPersonAtMin: 3500,
    category: "Referral Squad"
  }
];
