export const DEFAULT_SERVICES = [
  {
    id: "service_1",
    sellerId: "seller_plumber_joe",
    seller: "JoeThePlumber",
    title: "Expert Plumbing Service",
    price: 800,
    segment: "services",
    transactionType: "book",
    type: "image",
    url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Reliable plumbing service for emergency repairs, pipe fitting, and maintenance. Available 24/7.",
    isVerified: true,
    reviewCount: 45,
    ratingSum: 215,
    category: "Home Maintenance",
    priceModel: "per_hour"
  },
  {
    id: "service_2",
    sellerId: "seller_clean_home",
    seller: "CrystalClean",
    title: "Full House Deep Cleaning",
    price: 5000,
    segment: "services",
    transactionType: "book",
    type: "image",
    url: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=80",
    description: "Professional deep cleaning service including carpets, windows, and kitchen sanitization.",
    isVerified: true,
    reviewCount: 120,
    ratingSum: 580,
    category: "Cleaning",
    priceModel: "per_event"
  },
  {
    id: "service_3",
    sellerId: "seller_tutor_math",
    seller: "MathGenius",
    title: "Advanced Mathematics Tutoring",
    price: 1200,
    segment: "services",
    transactionType: "book",
    type: "image",
    url: "https://images.unsplash.com/photo-1510531704581-5b28709e5a11?auto=format&fit=crop&w=600&q=80",
    description: "One-on-one mathematics tutoring for high school and college students.",
    isVerified: true,
    reviewCount: 30,
    ratingSum: 148,
    category: "Education",
    priceModel: "per_hour"
  },
  {
    id: "service_4",
    sellerId: "seller_electrician",
    seller: "SparkyElectrics",
    title: "Residential Electrical Wiring",
    price: 1500,
    segment: "services",
    transactionType: "book",
    type: "image",
    url: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80",
    description: "Safe and guaranteed electrical wiring, appliance installation, and fault finding.",
    isVerified: false,
    reviewCount: 15,
    ratingSum: 65,
    category: "Home Maintenance",
    priceModel: "per_hour"
  }
];
